# Karma configuration
# Generated on Thu Nov 06 2014 20:47:03 GMT+0100 (CET)

module.exports = (config) ->
  config.set
    # base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: './'

    # frameworks to use
    # available frameworks: https:#npmjs.org/browse/keyword/karma-adapter
    frameworks: [
      'jasmine'
      'requirejs'
    ]

    files: [
      'test/test-main.js'
      {
        pattern: 'bower_components/lodash/lodash.js'
        included: false
      }
      {
        pattern: 'coffee/**/*.coffee'
        included: false
      }
      {
        pattern: 'test/**/*Spec.coffee'
        included: false
      }
    ]

    exclude: [ 'coffee/main.coffee' ]

    # preprocess matching files before serving them to the browser
    # available preprocessors: https:#npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: '**/*.coffee': [ 'coffee' ]
    coffeePreprocessor:
      options:
        bare: true
        sourceMap: false
      transformPath: (path) ->
        path.replace /\.coffee$/, '.js'

    reporters: [ 'progress' ]

    port: 9876

    colors: true

    # level of logging
    # possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO

    autoWatch: false

    browsers: [ 'PhantomJS' ]

    # Continuous Integration mode
    # if true, Karma captures browsers, runs the tests and exits
    singleRun: true
  return

# ---
# generated by js2coffee 2.1.0
